<?php

/**
 * @file
 * Handles installation for Commerce Australia Post module.
 */

/**
 * Implements hook_uninstall().
 */
function commerce_australia_post_uninstall() {
  $fields = array(
    'commerce_australia_post_api_key',
    'commerce_australia_post_postal_code',
    'commerce_australia_post_services',
    'commerce_australia_post_default_package_size_length',
    'commerce_australia_post_default_package_size_width',
    'commerce_australia_post_default_package_size_height',
    'commerce_australia_post_rates_timeout',
    'commerce_australia_post_show_description',
    'commerce_australia_post_log',
  );

  foreach ($fields as $data) {
    variable_del($data);
  }
}

