commerce_shipping.commerce_shipping_method.plugin.auspost:
  type: commerce_shipping_method_configuration
  mapping:
    api_information:
      label: 'API information'
      type: mapping
      mapping:
        api_key:
          type: string
          label: 'API key'
    options:
      type: mapping
      label: 'Australia Post Options'
      mapping:
        packaging:
          type: label
          label: 'Packaging Strategy'
        insurance:
          type: boolean
          label: 'Include Insurance'
        log:
          type: mapping
          label: 'Log the following messages for debugging'
          mapping:
            request:
              type: field.value.boolean
              mapping:
                value:
                  label: 'API request messages'
            response:
              type: field.value.boolean
              mapping:
                value:
                  label: 'API response messages'
